### ISSUE TITLE
yml

### ISSUE THREAD

**Issue by cfeng16** [danilotpnta/Youtube-Whisper#2]
Great work! Where is the environment.yml? Thanks!

**Comment by GerardDu** [comment]
I also want to know

**Comment by hhhizzz** [comment]
Searched the commit history, it looks like the author removed it: https://github.com/danilotpnta/Youtube-Whisper/commit/f3d3b524c6de2960bf79174ea51267b84af7e257#diff-9efd195f4e9bfb79ccd456a1d8370fafcc4bcb0b00ea3799222667d2ae818533

```yaml
name: yt-whisper-2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - selenium
      - requests
      - gradio
      - openai-whisper @ git+https://github.com/openai/whisper.git
```
